/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MbAmbulanceWlList {
    }
}
declare global {
    interface HTMLMbAmbulanceWlListElement extends Components.MbAmbulanceWlList, HTMLStencilElement {
    }
    var HTMLMbAmbulanceWlListElement: {
        prototype: HTMLMbAmbulanceWlListElement;
        new (): HTMLMbAmbulanceWlListElement;
    };
    interface HTMLElementTagNameMap {
        "mb-ambulance-wl-list": HTMLMbAmbulanceWlListElement;
    }
}
declare namespace LocalJSX {
    interface MbAmbulanceWlList {
    }
    interface IntrinsicElements {
        "mb-ambulance-wl-list": MbAmbulanceWlList;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "mb-ambulance-wl-list": LocalJSX.MbAmbulanceWlList & JSXBase.HTMLAttributes<HTMLMbAmbulanceWlListElement>;
        }
    }
}
